# Generated by Django 6.0.6 on 2026-07-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_solicitudvendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='requiere_aprobacion',
            field=models.BooleanField(default=False),
        ),
    ]
