# Generated by Django 5.2.10 on 2026-07-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0004_empresa_suscripcion_activa_empresa_tipo_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_vencimiento_prueba',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_plan',
            field=models.CharField(choices=[('TRIAL', 'Prueba 14 Días'), ('PREMIUM', 'Premium')], default='TRIAL', max_length=10),
        ),
    ]
