# Generated by Django 5.2.10 on 2026-07-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0005_empresa_fecha_vencimiento_prueba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='direccion_principal',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/empresas/'),
        ),
        migrations.AddField(
            model_name='tendero',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/tenderos/'),
        ),
        migrations.AddField(
            model_name='tendero',
            name='referencias',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/vendedores/'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='zona_cobertura',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
