# Generated by Django 5.2.10 on 2026-07-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0006_empresa_direccion_principal_empresa_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bot_voz_activa',
            field=models.BooleanField(default=False, verbose_name='Activar respuestas por voz del Tigre Bot'),
        ),
        migrations.AddField(
            model_name='tendero',
            name='bot_voz_activa',
            field=models.BooleanField(default=False, verbose_name='Activar respuestas por voz del Tigre Bot'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='bot_voz_activa',
            field=models.BooleanField(default=False, verbose_name='Activar respuestas por voz del Tigre Bot'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solicitudvendedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tendero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
