# Generated by Django 6.0.6 on 2026-07-24 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0007_empresa_bot_voz_activa_tendero_bot_voz_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comision_generada',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comision_pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_empresa', to='negocio.empresa'),
        ),
    ]
